# Generated by Django 6.0.3 on 2026-04-17 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_reviewrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewRating',
        ),
    ]
