# Generated by Django 6.0.3 on 2026-04-27 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_varient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varient',
            name='color',
        ),
        migrations.RemoveField(
            model_name='varient',
            name='stock',
        ),
    ]
