# Generated by Django 6.0.3 on 2026-04-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_varient_color_remove_varient_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='varient',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
