# Generated by Django 6.0.3 on 2026-04-27 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_varient_is_available'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Varient',
        ),
    ]
