# Generated by Django 6.0.3 on 2026-04-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50, unique=True, verbose_name='Category Name')),
                ('cat_slug', models.SlugField(unique=True, verbose_name='Category Slug')),
                ('cat_image', models.ImageField(blank=True, upload_to='photos/categories', verbose_name='Category Image')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
    ]
