# Generated by Django 6.0.3 on 2026-04-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Category Icon'),
        ),
    ]
